// Mozilla User Preferences for GTKless

// DO NOT EDIT THIS FILE WHILE USING 'FIREFOX GTKLESS'.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.

user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("widget.content.allow-gtk-dark-theme", true);
user_pref("widget.content.gtk-theme-override", "Adwaita");
user_pref("widget.gtk.alt-theme.accent", false);
user_pref("widget.gtk.alt-theme.scrollbar_active", false);
user_pref("widget.gtk.alt-theme.selection", false);
user_pref("widget.gtk.overlay-scrollbars.enabled", false);
user_pref("widget.gtk.theme-scrollbar-colors.enabled", false);
user_pref("layout.css.color-mix.enabled", true);
user_pref("browser.tabs.inTitlebar", 1);
